spring:
  application:
    name: "Tester Finder"
  profiles:
    active: "development"

server:
  port: 8120

management:
  server:
    port: 8120
    base-path: /management
  endpoints:
    web:
      exposure:
        include: info,health,metrics,loggers

datasource:
  files:
    testersFilePath: 'C:\testerFinder\testers.csv'
    devicesFilePath: 'C:\testerFinder\devices.csv'
    testerDevicesMappingFilePath: 'C:\testerFinder\tester_device.csv'
    bugsFilePath: 'C:\testerFinder\bugs.csv'